SET SERVEROUTPUT ON SIZE UNLIMITED

BEGIN EXECUTE IMMEDIATE 'DROP TABLE Detalle_Factura CASCADE CONSTRAINTS'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE Factura CASCADE CONSTRAINTS'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE resultados CASCADE CONSTRAINTS'; EXCEPTION WHEN OTHERS THEN NULL; END;
/

BEGIN
    DBMS_OUTPUT.PUT_LINE('Tablas borradas: Factura, Detalle_Factura, resultados');
END;
/
